name: Dev Checks

on:
  pull_request:
    paths-ignore: [.vscode/**, .github/**]
    branches: [dev]

jobs:
  # Checks that the app has been formatted with Prettier
  check-prettier:
    runs-on: ubuntu-latest
    timeout-minutes: 4

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Check Prettier
        run: npm run check-format

  # Checks that the Angular app successfully builds using ahead-of-time compilation
  build:
    runs-on: ubuntu-latest
    needs: [check-prettier]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing dependencies
        run: npm i

      - name: Building Angular web project
        run: npm run build

  # Checks that the Angular app passes all defined unit and integration tests
  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 8

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Installing dependencies
        run: npm ci --no-audit

      - name: Running all unit and integration tests
        run: npm run test-ci
